name: 'card_shuffler'
version: 0.0.2
description: A Polymer Dart application that loads up a deck of cards, displays them, and allows the user to shuffle them.

environment:
  sdk: '>=1.9.0 <2.0.0'

dependencies:
  browser: ^0.10.0
  polymer_elements: ^1.0.0-rc.5
  logging: any
  intl: any
  autonotify_observe: ^1.0.0-rc.10

transformers:
- autonotify_observe:
    entry_points:
    - web/index.html
- $dart2js:
    $include: '**/*.bootstrap.initialize.dart'
    minify: true
    commandLineOptions:
    - --trust-type-annotations
    - --trust-primitives
