name: card_shuffler
description: A Polymer Dart application that loads up a deck of cards, displays them, and allows the user to shuffle them.
dependencies:
  polymer: ">=0.10.0"
transformers:
- polymer:
    entry_points: web/index.html
